### PR TITLE
Adding a French translation

### PR DESCRIPTION
**Pull request by Atnode**
Hello everyone,
here is a French translation for DOS Coreutils.

Changes:
- Addition of a README in French,
- Modification of dosc.h and config.h to allow the compilation of a French version,
- Added translated binaries.

### CODE REVIEW

**Comment by ercanersoy** [comment]
What version of Open Watcom are you compile these binaries?

**Comment by Atnode** [comment]
Ah, I'm using Open Watcom 1.9.
I will correct that.

**Comment by Atnode** [comment]
Normally it's good.

**Comment by ercanersoy** [comment]
Thanks for your work.

**Pull request merged**
