### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by LiquidFox1776**
Some library code was added based off of GNU glibx under the LIB directory. A build.bat file was added to automate the build process, a new command dirname was added. A makefile was added for the library and the makefile for the commands was updated. The en.h lang file header was also updated

### CODE REVIEW

**Comment by ercanersoy** [comment]
I see previous commits on this pull request. Previous commits on previous pull requests have been applied.

**Comment by LiquidFox1776** [comment]
The batch file calls wmake to use the makefiles. I added another makefile for the LIB code and figured it would be easier to run a single batch file to help automate the process. There is a 'clean' option for the batch file that removes existing obj, com, and exe files as well.

**Comment by ercanersoy** [comment]
May you resolve conflicting files?

**Comment by ercanersoy** [comment]
Makefile in the lib directory may be called main Makefile or DOS Coreutils may use single Makefile.
Batch files may cause confuse.

**Comment by LiquidFox1776** [comment]
I can merge the two makefiles into a single one. and I can resolve the conflicting files. The code from getopt, basename and dosname come from gnulib https://github.com/coreutils/gnulib/tree/master/lib. I just modified them a little bit to get it to work with Open Watcom. My thought process was to port portions of gnulib to FreeDOS so we could use as much of the existing gnu coreutils source code for this project as possible.

**Comment by LiquidFox1776** [comment]
I merged the makefiles deleted the batch file, and made the filenames in lowercase.
How many spaces would you like to expand the tab character too for future references?

**Comment by ercanersoy** [comment]
Makefile should include tab character.

**Comment by ercanersoy** [comment]
Why are you using fputs() on "dirname.c"? I'm using puts().

**Comment by LiquidFox1776** [comment]
The code for dirname.c came from GNU Coreutil, and thats the way they had programmed the utility. I can change it to puts.

**Comment by ercanersoy** [comment]
May you change fputs to puts?

**Comment by ercanersoy** [comment]
Why you change Makefile CC and LD variables? DOS Coreutils should be compiled Open Watcom.

**Comment by ercanersoy** [comment]
Changing fputs to puts is not necessarry. I'm controlling and commenting these commits now.

**Comment by ercanersoy** [comment]
I remove asteriks in Makefile. We don't need these.

**Comment by ercanersoy** [comment]
Thanks for these commits. But, I can't build DOS Coreutils with these commits. If you would like add features, you may seperate pull requests. But, commtis shouldn't cause conflicts.

**Comment by ercanersoy** [comment]
If you would like get in contact with me, you may e-mail to me.

**Comment by ercanersoy** [comment]
Where you get code that on dosc.h and contributed by you?

**Comment by LiquidFox1776** [comment]
Some of the code came from or was based on code frome the GNU Coreutil system.h file found at https://github.com/coreutils/coreutils/blob/master/src/system.h , some of the code I wrote on my own.

**Pull request merged**
