### PR TITLE
Added base64 and more library files

### PR DESCRIPTION
**Pull request by LiquidFox1776**
Added base64 and more library files, updated Makefile to build base64 and new lib files. Made some functions and made some changes to dosc.h. Added some instructions to the Readme file.

### CODE REVIEW

**Comment by ercanersoy** [comment]
Thanks for your work.

I will merge this pull request. But, it needs some updates.

You may copy updated English strings in "en.h" to "fr.h" and "tr.h".
You may compile English binaries, French binaries and Turkish binaries by Open Watcom version 2.0-2017-11-01.

Open Watcom link: [https://sourceforge.net/projects/openwatcom/files/](https://sourceforge.net/projects/openwatcom/files/)

May you update this pull request?

**Comment by ercanersoy** [comment]
You may use DOSBox.

DOSBox link: [http://www.dosbox.com/](http://www.dosbox.com/)

**Comment by ercanersoy** [comment]
The language files coding DOS codepage. Not UTF-8.

For Turkish Language: 857
For French Language: 858

**Comment by ercanersoy** [comment]
If you would like commit, you may use git program on your computer. Uploading files via upload directly on browser causes encoding problem.

**Comment by LiquidFox1776** [comment]
DOS Box  won't run the Open Watcom installer either.
dosbox error

**Comment by ercanersoy** [comment]
You may using DOS32A.

DOS32A link: [http://dos32a.narechk.net/index_en.html](http://dos32a.narechk.net/index_en.html)

Usage: You should copy "DOS32A.EXE" to same directory of "OPENWAT2.EXE". Then run command line: DOS32A OPENWAT2.EXE

**Comment by ercanersoy** [comment]
You may use FreeDOS with DOS32A.

**Comment by ercanersoy** [comment]
These language files are correct.
If you will commit the executable files, I will merge this pull request.

**Comment by LiquidFox1776** [comment]
The Open Watcom 2 installer still crashed when using the dos32a DOS extender so I am trying to build Open Watcom 2 from the source code

**Comment by ercanersoy** [comment]
You may using newer version of DOS4GW.

**Comment by LiquidFox1776** [comment]
I have Open Watcom 2 installed, I will upload the binaries sometime soon. Some of the strings are missing from the fr.h and tr.h files so I will update those as well

**Comment by ercanersoy** [comment]
Thanks for your work.

**Comment by ercanersoy** [comment]
If you would like contribute DOS Coreutils, you may solve these issues.

[https://github.com/ercanersoy/DOS-Coreutils/issues](https://github.com/ercanersoy/DOS-Coreutils/issues)

**Pull request merged**
