### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Atnode**
- Updating Turkish README,
- Updating English README.

### CODE REVIEW

**Comment by ercanersoy** [comment]
Will not merge. Because, README's shouldn't Markdown type.

**Comment by Atnode** [comment]
Okay, I remove the markdown to just keep the useful changes.

**Comment by Atnode** [comment]
It's done.

**Comment by ercanersoy** [comment]
What changes are you done?

**Comment by Atnode** [comment]
There I deleted the markdown of the previous commit.
The main changes are the synchronization with the last changes of the main README.md plus typographical corrections.

**Comment by ercanersoy** [comment]
Thanks for your work.

**Pull request merged**
